### ISSUE TITLE
Where can I find proposals from the third-party offers (not from the Dart developers) and what will be their perspective?

### ISSUE THREAD

**Issue by mezoni** [dart-lang/dart_enhancement_proposals#16]
Where can I find proposals from the third-party offers (not from the Dart developers)?

Also another related question:
What are the chances that the offer made by the external person (not a member of the Dart Team) will be taken to the implementation immediately after the approval?

Eg.

Assume that some external person (not a member of the Dart Team) will place here a proposal (specification) follow the defintion taken from [Dart issue tracker](https://code.google.com/p/dart/issues/list).
By example, proposal for [Support declaration of generic type for methods] (https://code.google.com/p/dart/issues/detail?id=254)

- What are the chances that proposal created from the issue tracker will be approved?
- What are the chances that after the approval of this proposal the work will be immediately began in this assignment?

**Comment by mezoni** [comment]
I ask this because even Gilad Bracha wrote about this enhancement at Nov 3, 2011:

[We've tried to keep things very simple. but this is obviously a possible enahncement.](https://code.google.com/p/dart/issues/detail?id=254#c2)

If it possible then it should be proposed here (dart enhancement proposal). Right?

And if I understand correctly, the purpose of the Dart DEP is exactly what fundamentally determines the fate of wishes expressed by the stakeholders (eg. the common members of the Dart community).

**Comment by munificent** [comment]
There are currently no DEPs that have proposed from people outside of the Dart team. This isn't surprising since the DEP process was only launched last week and building up a proposal and consensus for it takes some time.

I don't know what the chances are of a proposal being accepted. It depends entirely on the kinds of proposals we get, which we don't know yet.

**Comment by eernstg** [comment]
Proposals should be accepted based on their inherent merits, not based on
the affiliations of the proposer(s). However, there is no guarantee that
any proposal (by a Googler or anyone else) will be adopted, nor that an
adopted proposal will remain exactly the same all the way to a final
specification and implementation---in fact, it is very unlikely that any
accepted proposal will remain the same all the way.  If the proposal is
backed up by a high quality implementation then it is of course much easier
to refine and integrate that implementation into the most recent version of
the Dart tools, but even in that case there will not be any unconditional
guarantees about the delay from the proposal has been accepted until it is
implemented in the tools.

On Tue, Mar 10, 2015 at 5:27 PM, Bob Nystrom <notifications@github.com>
wrote:

> There are currently no DEPs that have proposed from people outside of the
> Dart team. This isn't surprising since the DEP process was only launched
> last week and building up a proposal and consensus for it takes some time.
>
> I don't know what the chances are of a proposal being accepted. It depends
> entirely on the kinds of proposals we get, which we don't know yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/16#issuecomment-78090653>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mezoni** [comment]
@eernstg 

>> If the proposal is backed up by a high quality implementation then it is of course much easier to refine and integrate that implementation into the most recent version of the Dart tools, but even in that case there will not be any unconditional guarantees about the delay from the proposal has been accepted until it is implemented in the tools.

So, why then need Google engineers, language designers, programmers, consultants, experts and so on if the cannot implement a proposal without a good proposal about the way how to do high quality implementation?
Eg.

- I propose "async/await"
- All vote: "We agree"

And what happens?
Nothing!
Why?
Because I forgotten to specify the way of high quality implementation?
Does this means that all proposals from Google will be implemented (despite the lack of specifications about high quality implementation) and all other (non Google proposals) can be simple rejected?
Or maybe they will be accepted but remains unimplemented due the lack of specifications about high quality implementation.
So, I cannot understand your position because it is a very strange.
Why need to accept if it impossible implement?
Why need to propose if there is no chance?

**Comment by eernstg** [comment]
But surely you acknowledge that a high quality implementation of any
feature offered by the Dart tools is imperative, and also that such an
implementation does not jump into existence without any effort, and efforts
are limited by the available resources, no matter how much we wish to
implement any given thing "now"?  And surely you acknowledge that one way
to push a proposal is to provide solid evidence that it works?

By the way, async/await is under construction because very smart people
have been working very hard on it for a while---that's not nothing.

On Tue, Mar 10, 2015 at 9:24 PM, mezoni <notifications@github.com> wrote:

> @eernstg <https://github.com/eernstg>
>
>  If the proposal is backed up by a high quality implementation then it is
> of course much easier to refine and integrate that implementation into the
> most recent version of the Dart tools, but even in that case there will not
> be any unconditional guarantees about the delay from the proposal has been
> accepted until it is implemented in the tools.
>
>  So, why then need Google engineers, language designers, programmers,
> consultants, experts and so on if the cannot implement a proposal without a
> good proposal about the way how to do high quality implementation?
> Eg.
>
>    - I propose "async/await"
>    - All vote: "We agree"
>
> And what happens?
> Nothing!
> Why?
> Because I forgotten to specify the way of high quality implementation?
> Does this means that all proposals from Google will be implemented
> (despite the lack of specifications about high quality implementation) and
> all other (non Google proposals) can be simple rejected?
> Or maybe they will be accepted but remains unimplemented due the lack of
> specifications about high quality implementation.
> So, I cannot understand your position because it is a very strange.
> Why need to accept if it impossible implement?
> Why need to propose if there is no chance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/16#issuecomment-78140110>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mezoni** [comment]
@eernstg 

>> By the way, async/await is under construction because very smart people have been working very hard on it for a while---that's not nothing.

I am also smart person and what?
Or do you think that only Dart developers are smart?

>> By the way, async/await is under construction because very smart people have been working very hard on it for a while---that's not nothing.

For that who know this is not hard.
Also because Dart VM is not a modular your implementation of "async/await" is worse then in .NET.
In .NET it implemented as "state machine" produced by the generator but in Dart VM it (as always) hard-coded implementation.
Maintaining the generator is easy then the hard-coded, in different places, implementation.

This implementation is correct but it generates very slow code.
https://github.com/dart-lang/async_await

Typescript proposes much more faster proposal based on the state machine.

Eg.

```js
function fn() {  
    var i;  
    return new Promise(function (_resolve) {  
        resolve(__awaiter(__generator(function (_state) {  
            switch (_state.label) {  
                case 0:  
                    _state.trys = [];  
                    _state.label = 1;  
                case 1:  
                    _state.trys.push([1, 3, 4, 6]);  
                    return [3 /*yield*/, p0];  
                case 2:  
                    return [5 /*break*/, 6];  
                case 3:  
                    _a = _state.error;  
                    alert(_a.message);  
                    return [5 /*break*/, 6];  
                case 4:  
                    return [3 /*yield*/, p1];  
                case 5:  
                    return [6 /*endfinally*/];  
                case 6:  
                    return [2 /*return*/];  
            }  
        }));  
    });  
    var _a;  
}
```

The better way is to implement them with the generator of the state machine with "goto" statements.

Since Dart does not support the "goto" statements then they can eliminated through the well known algorithms in last stages of generator.
This kind of implementation of "async/await" would be fastest as in the .NET

**Comment by eernstg** [comment]
On Wed, Mar 11, 2015 at 1:34 PM, mezoni <notifications@github.com> wrote:

> @eernstg <https://github.com/eernstg>
>
>  By the way, async/await is under construction because very smart people
> have been working very hard on it for a while---that's not nothing.
>
>  I am also smart person and what?
> Or do you think that only Dart developers are smart?
>
Please try to be reasonable.  Even smart people can benefit from that now
and then.  ;-)

>  By the way, async/await is under construction because very smart people
> have been working very hard on it for a while---that's not nothing.
>
>  For that who know this is not hard.
>
So you start off being offended because a positive attribute is associated
with someone who's not you (apparently, we couldn't ever mention a positive
attribute in association with anybody without remembering to add a remark
about the potentially large number of other people who might also have this
positive attribute), and immediately you continue with something that could
hardly mean anything other than "designing and implementing the Dart
language support for async/await is not hard".

Have you heard about Kant's categorical imperative ("Act only according to
that maxim whereby you can at the same time will that it should become a
universal law")?  Basically, if you insist on being offended by something
which doesn't imply anything negative about you in the first place, and
then immediately accuse someone else of being unable to do something that
is not hard, then you have certainly positioned yourself pretty far away
from that rule.

I'm not going to stop entirely responding to your input, but you must
understand that communication with other people works better if there is a
certain symmetry to it.  Kant's categorical imperative is not a bad place
to start.

> Also because Dart VM is not a modular your implementation of "async/await"
> is worse then in .NET.
> In .NET it implemented as "state machine" produced by the generator but in
> Dart VM it (as always) hard-coded implementation.
> Maintaining the generator is easy then the hard-coded, in different
> places, implementation.
>
Well, the .NET state machine generation is hard-coded in the relevant .NET
tools, so the level of malleability is comparable.  Whether it's easier to
maintain one or the other implementation is probably not trivial to
determine, but I agree that the syntactic sugar approach taken in .NET can
be quite accessible when inspecting the implementation of a compiler.
There are so many other things to take into account, though, and you may or
may not know that dart2js uses a continuation-passing-style transformation,
but that is yet another approach to consider.

Note also that async/await in .NET and in Dart is not the same thing.  You
probably know that Eric Meijer has contributed to both designs, and the
Dart design is

> This implementation is correct but it generates very slow code.
> https://github.com/dart-lang/async_await
>
But this is the dart2js implementation. For the vm you'd need to look into
something like
https://github.com/dart-lang/bleeding_edge/tree/master/dart/runtime/vm.

> Typescript proposes much more faster proposal based on the state machine.
>
> Eg.
>
> function fn() {
>     var i;
>     return new Promise(function (_resolve) {
>         resolve(__awaiter(__generator(function (_state) {
>             switch (_state.label) {
>                 case 0:
>                     _state.trys = [];
>                     _state.label = 1;
>                 case 1:
>                     _state.trys.push([1, 3, 4, 6]);
>                     return [3 /*yield*/, p0];
>                 case 2:
>                     return [5 /*break*/, 6];
>                 case 3:
>                     _a = _state.error;
>                     alert(_a.message);
>                     return [5 /*break*/, 6];
>                 case 4:
>                     return [3 /*yield*/, p1];
>                 case 5:
>                     return [6 /*endfinally*/];
>                 case 6:
>                     return [2 /*return*/];
>             }
>         }));
>     });
>     var _a;
> }
>
> The better way is to implement them with the generator of the state
> machine with "goto" statements.
>
In fact, async/await could be viewed as a poor man's version of
co-routines, i.e., an approach to non-sequential execution that differs
from threads by having explicit switch of control and in return greatly
reducing the complexity of reasoning about race conditions and other
concurrency conflicts.  With a well-designed treatment of runtime stacks
(and their attachment/detachment at suspend/resume actions on
co-routines).  State machines are effectively emulating those runtime
stacks and stack operations, and I find it unlikely that a source-to-source
approach will be able to express a similarly well-optimized implementation
as that which is possible when the runtime representation can be tailored
and exploited in full for that purpose.

In .NET they couldn't do that because they couldn't introduce the required
semantic support on the CLR side.

I'm sure some very smart people ;) at Microsoft have done a very good job
of compiling async/await using state machines, but I doubt that this is an
inherently superior approach.

> Since Dart does not support the "goto" statements then they can eliminated
> through the well known algorithms in last stages of generator.
>
Oops, I thought you insisted on a source-to-source approach for
implementation maintainability?  ;-)

> This kind of implementation of "async/await" would be fastest as in the
> .NET
>
That one I wasn't so sure about.  But thanks for the input!

  best regards,

-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by mezoni** [comment]
@eernstg 

Thank you.
In think that the people from MS mostly write their software after reading books, scientific papers and after their own research (including laboratory experiments with a testing, profiling and forecasting).
And of course, using common sense. In all the details.

**Comment by eernstg** [comment]
True, lots of nice work has come from MS language people (research and
production).

On Mon, Mar 16, 2015 at 1:02 PM, mezoni <notifications@github.com> wrote:

> @eernstg <https://github.com/eernstg>
>
> Thank you.
> In think that the people from MS mostly write their software after reading
> books, scientific papers and after their own research (including laboratory
> experiments with a testing, profiling and forecasting).
> And of course, using common sense. In all the details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dart_enhancement_proposals/issues/16#issuecomment-81607235>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984
