### ISSUE TITLE
DEP003:  Allow closurizing instance method from class

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dart_enhancement_proposals#17]
(Since this is an accepted DEP, I assumed issues should be filed here rather than the original repo)

Often when one wants to closurize a method, they don't yet have an object in hand to do so.  Instead they want a closure which takes an object of a given type as the first parameter, and then any parameters accepted by the closurized method of that type.

Examples:

`Object#toString` => `(Object _) => _.toString()`
`num#+` => `(num _, num other) => _ + other`
`int#+` => `(int _, num other) => _ + other`

**Comment by munificent** [comment]
It is definitely the case that I often want to partially apply the arguments, but not the receiver for a method call. I brought this up with the original proposal, but it didn't seem to go anywhere.

I'm honestly not sure where feedback for this should go since the DEP is accepted. I'll email the committee and see what they think.

**Comment by munificent** [comment]
Gilad says the proposal deliberately doesn't do this, so I guess the right thing to do here is close the bug. If you'd like another language change to enable this, it would be its own DEP.
