### ISSUE TITLE
Non-null types and non-null by default (NNBD)

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart_enhancement_proposals#30]
- Home: https://github.com/chalin/DEP-non-null
- Proposal [PDF](https://github.com/chalin/DEP-non-null/raw/master/doc/dep-non-null.pdf)

*Edit: The language team is now working on adding non-nullable types to Dart: https://github.com/dart-lang/language/issues/110. Much of that work is inspired by and directly uses ideas in this proposal (including the name!). However, we aren't using this issue to track that work, so I'm closing it out. https://github.com/dart-lang/language/issues/110 is where the action is now.*

**Comment by JayAndCatchFire** [comment]
It's been two and a half years since this was introduced.  Can we get an overall status report?  Is this a feature that the Dart core team is committed to?

I ask because having the type system of a language deal with nulls so that developers don't have to do null checks everywhere or risk null pointer exceptions from practically anywhere is kind of a killer feature for me.

Kotlin has non-nullable by default.  Clojure has nil-punning.  Haskell and family side-steps this using Maybe/Nothing monads.  This is, believe it or not, my number one biggest ask for Dart.

**Comment by franklinyu** [comment]
TypeScript also has this (although not enabled by default).

**Comment by leafpetersen** [comment]
We're very focused on getting Dart 2 out the door right now.  Once that's out (very soon), I'm hoping that we can put effort into this.

**Comment by ohjames** [comment]
If this feature comes to Dart, and I really hope it does, it should really be done in concert with union types (https://github.com/dart-lang/sdk/issues/4938). That's the only feature Dart is lacking that I think is even more important than this one.

**Comment by harindaka** [comment]
Wow I just started on Dart and was surprised that you can assign null to ints. This is so not intuitive. Nullable value types should be opt in. i.e. int? in C# It might be too late to change the current implementation however can something like int! be done to explicitly disallow null assignments?

**Comment by touseefbsb** [comment]
dart is a very good language but considering it is a web language and also now a major part of flutter, so for its success it is crucial that it tries its best to compete with c#, kotlin and swift, and those 3 languages are brilliant and powerful, I hope dart catches on to them ASAP.

**Comment by munificent** [comment]
> I hope dart catches on to them ASAP.

Me too, my friend.

**Comment by munificent** [comment]
Edited the original description to point to the new tracking issue and closed this.
