### ISSUE TITLE
Metadata for Type Annotations

### ISSUE THREAD

**Issue by chalin** [dart-lang/dart_enhancement_proposals#32]
https://github.com/chalin/DEP-metadata-for-type-annotations

**Comment by lrhn** [comment]
We are not currently planning to add these extra annotation points. 
The current approach to annotations is that you can annotate any *declaration*, but not any *expression* or *type*. That is, annotations are not modifiers on values/types, they are metadata on things that have a declared name.

Since the DEP process has been abandoned, if there is still a wish for this change, it should be refiled in the [language](https://github.com/dart-lang/language) repository.
